/**
 * Shape of the derived set-logo mapping files under scripts/data/set-logos/
 * (e.g. pokellector-ja.json), read by scripts/backfill-set-logo-url.ts and
 * scripts/backfill-set-name-en.ts alongside their hand-curated tables
 * (scripts/data/pokemon-set-logos.ts / pokemon-set-translations.ts).
 *
 * Machine-generated by scripts/crawl-pokemon-set-logos-pokellector.ts, same
 * convention as scripts/data/card-images/types.ts: a `verified` file-level
 * gate a human flips only after spot-checking rows against the live source,
 * plus a per-entry sourceUrl/sourceName so every row stays auditable.
 */

export interface SetLogoEntry {
  /** Must equal Set.id exactly, e.g. "pokemon:ja:M5". */
  setId: string;
  logoUrl: string;
  /**
   * English gloss of the set name as pokellector titles it, e.g. "Abyss
   * Eye". A candidate for Set.nameEn — pokellector is a fan site, not the
   * publisher, so treat this the same as any other unverified translation
   * source until spot-checked.
   */
  nameEn: string;
  /** The set-listing page this was read off, for attribution and re-checking. */
  sourceUrl: string;
  /** The set-listing button's own title text, kept for audit. */
  sourceName: string;
}

export interface SetLogoFile {
  gameId: string;
  sourceNote: string;
  verified: boolean;
  generatedAt: string;
  entries: SetLogoEntry[];
}

/**
 * Why a crawled set-logo candidate did NOT make it into the mapping file.
 *
 * The card-image review files have carried a machine-readable `reason` from
 * the start (see ../card-images/types.ts); these ones originally encoded it
 * as English prose appended to `sourceName`, which meant the review file
 * could be read by a human but not counted, filtered or diffed. Optional so
 * that already-generated files stay valid against this type.
 */
export type SetLogoReviewReason =
  /** The source's own listing has this code on more than one entry, so which set it means is ambiguous. */
  | "ambiguous-source-code"
  /** No Set row in our catalog has this code or name. */
  | "no-set-row"
  /** More than one Set row matched, so which one this logo belongs to is ambiguous. */
  | "ambiguous-set-match"
  /** A set matched by name, but its card count disagreed by more than the tolerance. */
  | "card-count-mismatch"
  /** The source page had no usable logo image for this set. */
  | "no-logo";

/** A set-listing entry that didn't match any Set row in the DB. */
export interface SetLogoReviewEntry {
  sourceCode: string;
  sourceUrl: string;
  sourceName: string;
  logoUrl: string;
  reason?: SetLogoReviewReason;
}

export interface SetLogoReviewFile {
  gameId: string;
  note: string;
  generatedAt: string;
  entries: SetLogoReviewEntry[];
}
