/**
 * Shape of the derived set-logo mapping files under scripts/data/set-logos/
 * (e.g. pokellector-ja.json), read by scripts/backfill-set-logo-url.ts and
 * scripts/backfill-set-name-en.ts alongside their hand-curated tables
 * (scripts/data/pokemon-set-logos.ts / pokemon-set-translations.ts).
 *
 * Machine-generated by scripts/crawl-pokemon-set-logos-pokellector.ts, same
 * convention as scripts/data/card-images/types.ts: a `verified` file-level
 * gate a human flips only after spot-checking rows against the live source,
 * plus a per-entry sourceUrl/sourceName so every row stays auditable.
 */

export interface SetLogoEntry {
  /** Must equal Set.id exactly, e.g. "pokemon:ja:M5". */
  setId: string;
  logoUrl: string;
  /**
   * English gloss of the set name as pokellector titles it, e.g. "Abyss
   * Eye". A candidate for Set.nameEn — pokellector is a fan site, not the
   * publisher, so treat this the same as any other unverified translation
   * source until spot-checked.
   */
  nameEn: string;
  /** The set-listing page this was read off, for attribution and re-checking. */
  sourceUrl: string;
  /** The set-listing button's own title text, kept for audit. */
  sourceName: string;
}

export interface SetLogoFile {
  gameId: string;
  sourceNote: string;
  verified: boolean;
  generatedAt: string;
  entries: SetLogoEntry[];
}

/** A pokellector set-listing entry that didn't match any Set row in the DB. */
export interface SetLogoReviewEntry {
  sourceCode: string;
  sourceUrl: string;
  sourceName: string;
  logoUrl: string;
}

export interface SetLogoReviewFile {
  gameId: string;
  note: string;
  generatedAt: string;
  entries: SetLogoReviewEntry[];
}
