/**
 * Shape of the derived image-mapping files that scripts/seed-card-images.ts
 * reads (pokemon-ja.json, pokemon-tw.json, ...).
 *
 * These are machine-generated by the crawlers rather than hand-written, which
 * is why they deviate from the per-entry `sourceNote` convention used by
 * scripts/data/pokemon-manual/types.ts: a hand-written note per row is
 * meaningless across ~15k rows. The convention's *intent* — every row's
 * sourcing is auditable, and nothing unverified reaches the database — is kept
 * via a per-entry sourceUrl + sourceName and a file-level `verified` gate that
 * a human flips only after reading the derive summary and spot-checking rows
 * against the live pages.
 *
 * Stored as JSON, not TS, because a 1.5MB checked-in .ts file measurably slows
 * typecheck and lint for data nothing imports as types.
 */

export interface CardImageEntry {
  /** Must equal CatalogItem.externalId exactly, e.g. "ja:SM10-034". */
  externalId: string;
  imageSmallUrl: string;
  imageLargeUrl: string;
  /** The page this was read off, for attribution and re-checking. */
  sourceUrl: string;
  /**
   * Card name as printed on the source page. Kept so the name guard that
   * gated this row stays auditable after the fact — if the mapping is ever
   * questioned, this is what it was matched against.
   */
  sourceName: string;
}

export interface CardImageFile {
  gameId: string;
  /** How this file was produced, incl. which script and when. */
  sourceNote: string;
  /** Seeding refuses files that aren't verified. Flipped by a human. */
  verified: boolean;
  generatedAt: string;
  entries: CardImageEntry[];
}

/** Why a crawled card did NOT make it into the mapping file. */
export type ReviewReason =
  | "unknown-set-code"
  | "no-catalog-row"
  | "name-mismatch"
  | "ambiguous-set"
  /**
   * The page loaded but didn't yield the fields needed to map it — e.g.
   * Diamond & Pearl-era JP pages print "DPBP#269" (a Pokédex-style number)
   * where modern ones print a collector number like "038 / 100". These are
   * listed rather than silently dropped, so the review file accounts for
   * every card the crawl actually found.
   */
  | "missing-page-fields"
  /**
   * crawl-pokemon-jp-uk-images.ts only: the catalog's Japanese name didn't
   * resolve to an English name via resolvePokemonCardNameEn (mostly Trainer/
   * Item/Energy cards outside the curated translation table) — nothing to
   * check the site's card against, so it's routed here instead of trusted.
   */
  | "unresolved-name-guard";

export interface CardImageReviewEntry {
  reason: ReviewReason;
  sourceId: number;
  sourceUrl: string;
  sourceName: string;
  /** What the crawler read off the page, before mapping. */
  sourceSetLabel: string;
  sourceNumber: string;
  /** The externalId we would have written, when one could be derived. */
  candidateExternalId?: string;
  /** For name-mismatch: what the catalog says the card is called. */
  catalogName?: string;
}

export interface CardImageReviewFile {
  gameId: string;
  note: string;
  generatedAt: string;
  entries: CardImageReviewEntry[];
}
